export function agentHomepage() {
  return {
    schemaVersion: "1.0",
    version: "1.0.0",
    mode: "agent",
    agentMode: true,
    mediaType: "application/json",
    machineReadable: true,
    type: "agent-capability-index",
    name: "UsageMax",
    description: "A public observability layer for bounded AI usage telemetry.",
    canonicalUrl: "https://usagemax.com/?mode=agent",
    capabilities: ["public aggregate usage", "leaderboard", "documentation", "pricing", "OpenAPI", "MCP", "A2A"],
    publicData: ["network totals", "public profiles", "bounded daily rollups", "bounded live activity"],
    exclusions: ["prompts", "completions", "credentials", "private workspace data"],
    authentication: {
      publicReads: "none",
      collectorWrites: "installation-bound write-only bearer token",
      website: "WorkOS AuthKit session; not an API token",
    },
    endpoints: [
      { name: "networkStats", method: "GET", path: "/api/stats", authentication: "none" },
      { name: "leaderboard", method: "GET", path: "/api/leaderboard", authentication: "none" },
      { name: "publicProfile", method: "GET", path: "/api/profiles/{handle}", authentication: "none" },
      { name: "collectorStatus", method: "GET", path: "/api/v1/devices/status", authentication: "collector bearer", readOnly: true, returnsSecret: false },
      { name: "snapshotStatus", method: "GET", path: "/api/v2/usage/snapshots/{runId}", authentication: "collector bearer + device UUID", readOnly: true, returnsSecret: false },
      { name: "openapi", method: "GET", path: "/openapi.json", authentication: "none" },
      { name: "mcp", method: "POST", path: "/mcp", authentication: "none", readOnly: true },
      { name: "sandbox", method: "POST", path: "/api/v1/sandbox/validate", authentication: "none", writes: false },
    ],
    resources: [
      { name: "openapi", url: "/openapi.json", contentType: "application/vnd.oai.openapi+json", authentication: "none", readOnly: true },
      { name: "mcp-discovery", url: "/.well-known/mcp", contentType: "application/json", authentication: "none", readOnly: true },
      { name: "a2a-agent-card", url: "/.well-known/agent-card.json", contentType: "application/json", authentication: "none", readOnly: true },
      { name: "agent-skills", url: "/.well-known/agent-skills/index.json", contentType: "application/json", authentication: "none", readOnly: true },
      { name: "pricing", url: "/pricing.md", contentType: "text/markdown", authentication: "none", readOnly: true },
      { name: "http-message-signatures-directory", url: "/.well-known/http-message-signatures-directory", contentType: "application/http-message-signatures-directory+json", authentication: "none", readOnly: true },
    ],
    protocols: {
      mcp: { endpoint: "/mcp", transport: "streamable-http", protocolVersion: "2025-06-18", authentication: "none", readOnly: true },
      a2a: { endpoint: "/a2a", transport: "json-rpc", authentication: "none", readOnly: true },
    },
    limits: {
      publicLeaderboardRows: 100,
      sandbox: { maxBytes: 16_384, maxEvents: 100, writes: false },
      mcp: { maxBodyBytes: 65_536, writes: false },
    },
    errors: { format: "application/json", schema: "/openapi.json#/components/schemas/Error", recovery: "/not-found.md" },
    links: {
      markdown: "/index.md",
      docs: "/docs",
      api: "/openapi.json",
      mcp: "/mcp",
      a2a: "/a2a",
      ask: "/ask",
      skills: "/.well-known/agent-skills/index.json",
      pricing: "/pricing",
      botAuthDirectory: "/.well-known/http-message-signatures-directory",
    },
    discovery: {
      llms: "https://usagemax.com/llms.txt",
      openapi: "https://usagemax.com/openapi.json",
      mcp: "https://usagemax.com/.well-known/mcp/server-card.json",
      a2a: "https://usagemax.com/.well-known/agent-card.json",
      authorizationServer: "https://usagemax.com/.well-known/oauth-authorization-server",
      protectedResource: "https://usagemax.com/.well-known/oauth-protected-resource",
      skills: "https://usagemax.com/.well-known/agent-skills/index.json",
    },
  };
}
