export function agentHomepage() {
  return {
    schemaVersion: "1.0",
    version: "1.0.0",
    mode: "agent",
    agentMode: true,
    mediaType: "application/json",
    machineReadable: true,
    type: "agent-capability-index",
    name: "UsageMax",
    docs: "https://usagemax.com/docs",
    pricing: "https://usagemax.com/pricing.md",
    sandbox: "https://usagemax.com/sandbox",
    pricingPlans: [
      {
        id: "personal",
        name: "Personal",
        price: { amount: 0, currency: "USD", interval: "month" },
        billing: "no_card_no_trial",
        features: ["private_history", "one_shot_syncs", "optional_public_profile", "bounded_exports"],
        limits: { linkedComputers: 25, budgets: 5, detailedRetentionDays: 30 },
      },
      {
        id: "small-teams",
        name: "Small teams",
        price: { amount: 0, currency: "USD", interval: "month" },
        billing: "no_card_no_trial",
        features: ["private_workspace", "invitations", "roles", "teams", "projects", "shared_reporting"],
        limits: { members: 10, teams: 5, projects: 20, devices: 25, detailedRetentionDays: 30 },
      },
      {
        id: "enterprise",
        name: "Enterprise",
        price: { amount: null, currency: "USD", interval: "month", qualifier: "custom_agreement" },
        billing: "written_agreement_before_activation",
        features: ["higher_capacity", "sso", "directory_setup", "private_attribution", "residency_choices", "governed_exports", "support_commitments"],
        limits: "contract_specific",
      },
    ],
    brand: {
      name: "UsageMax",
      url: "https://usagemax.com",
      logo: "https://usagemax.com/brand/icon-192.png",
      sameAs: ["https://github.com/SYMBaiEX/usagemax", "https://github.com/SYMBaiEX", "https://www.npmjs.com/package/usagemax", "https://registry.modelcontextprotocol.io/v0.1/servers/io.github.SYMBaiEX%2Fusagemax/versions/latest"],
    },
    description: "A public observability layer for bounded AI usage telemetry.",
    canonicalUrl: "https://usagemax.com/?mode=agent",
    purpose: "Help agents discover public UsageMax data, understand the collector boundary, and choose a safe integration path.",
    auth: "https://usagemax.com/auth.md",
    openapi: "https://usagemax.com/openapi.json",
    mcp: "https://usagemax.com/mcp",
    agentCard: "https://usagemax.com/.well-known/agent-card.json",
    skills: "https://usagemax.com/.well-known/agent-skills/index.json",
    capabilities: ["public aggregate usage", "leaderboard", "documentation", "pricing", "OpenAPI", "MCP", "WebMCP", "A2A"],
    integrations: [
      { name: "HTTP API", url: "https://usagemax.com/openapi.json", mode: "read-and-content-free-telemetry" },
      { name: "MCP", url: "https://usagemax.com/mcp", mode: "read-only" },
      { name: "Documentation MCP", url: "https://usagemax.com/docs-mcp", mode: "read-only" },
      { name: "WebMCP", url: "https://usagemax.com/webmcp", mode: "browser-local-read-only" },
      { name: "A2A", url: "https://usagemax.com/a2a", mode: "read-only" },
      { name: "CLI", url: "https://usagemax.com/cli.md", mode: "local-content-free-sync" },
    ],
    onboarding: {
      freeTier: true,
      noCardRequired: true,
      sandbox: {
        url: "https://usagemax.com/sandbox",
        endpoint: "https://usagemax.com/api/v1/sandbox/validate",
        method: "POST",
        writes: false,
        authentication: "none",
        request: "{events:[content-free event objects]}",
        response: "{ok:true,accepted:number,writes:false}",
      },
      firstSync: "bunx usagemax",
      steps: [
        {
          order: 1,
          action: "sign_in",
          url: "https://usagemax.com/sign-in",
          description: "Sign in with the hosted UsageMax browser flow when an account is required.",
          authentication: "WorkOS AuthKit session",
        },
        {
          order: 2,
          action: "link_computer",
          url: "https://usagemax.com/cli.md",
          command: "bunx usagemax",
          description: "Run the one-shot CLI on each computer to link it and upload bounded aggregate usage.",
          writes: "content-free aggregate telemetry only",
        },
        {
          order: 3,
          action: "verify",
          url: "https://usagemax.com/api/v1/devices/status",
          description: "Use the collector status endpoint to verify the linked device without exposing its secret.",
          authentication: "installation-bound collector bearer",
          readOnly: true,
        },
      ],
    },
    keyCapabilities: {
      read: ["network totals", "public profiles", "leaderboard", "bounded daily rollups", "bounded live activity"],
      write: ["content-free telemetry", "OpenTelemetry traces", "usage snapshots"],
      safety: ["public reads require no credential", "collector writes require an installation-bound bearer token", "sandbox validation never writes"],
    },
    publicData: ["network totals", "public profiles", "bounded daily rollups", "bounded live activity"],
    exclusions: ["prompts", "completions", "credentials", "private workspace data"],
    authentication: {
      publicReads: "none",
      collectorWrites: "installation-bound write-only bearer token",
      website: "WorkOS AuthKit session; not an API token",
      browserSignIn: "https://usagemax.com/sign-in",
      oauthDelegation: false,
    },
    responseFormats: {
      publicReads: ["application/json", "text/markdown"],
      collectorWrites: ["application/json"],
      errors: "application/json with machine-readable code and recovery hint",
    },
    endpoints: [
      { name: "networkStats", method: "GET", path: "/api/stats", authentication: "none" },
      { name: "leaderboard", method: "GET", path: "/api/leaderboard", authentication: "none" },
      { name: "publicProfile", method: "GET", path: "/api/profiles/{handle}", authentication: "none" },
      { name: "collectorStatus", method: "GET", path: "/api/v1/devices/status", authentication: "collector bearer", readOnly: true, returnsSecret: false },
      { name: "snapshotStatus", method: "GET", path: "/api/v2/usage/snapshots/{runId}", authentication: "collector bearer + device UUID", readOnly: true, returnsSecret: false },
      { name: "openapi", method: "GET", path: "/openapi.json", authentication: "none" },
      { name: "v1Namespace", method: "GET", path: "/api/v1", authentication: "collector bearer hint", readOnly: true, writes: false },
      { name: "mcp", method: "POST", path: "/mcp", authentication: "none", readOnly: true },
      { name: "sandbox", method: "POST", path: "/api/v1/sandbox/validate", authentication: "none", writes: false },
    ],
    api: {
      baseUrl: "https://usagemax.com/api",
      version: "v1",
      versionRoot: "https://usagemax.com/api/v1",
      openapi: "https://usagemax.com/openapi.json",
      publicReads: ["/api/stats", "/api/leaderboard", "/api/profiles/{handle}"],
      collectorWrites: ["/api/v1/telemetry/llm", "/api/v1/traces", "/api/v2/usage/snapshots"],
      sandbox: "https://usagemax.com/api/v1/sandbox/validate",
    },
    apiEndpoints: [
      { name: "networkStats", url: "https://usagemax.com/api/stats", method: "GET", authentication: "none", readOnly: true },
      { name: "leaderboard", url: "https://usagemax.com/api/leaderboard", method: "GET", authentication: "none", readOnly: true },
      { name: "publicProfile", url: "https://usagemax.com/api/profiles/{handle}", method: "GET", authentication: "none", readOnly: true },
      { name: "v1Namespace", url: "https://usagemax.com/api/v1", method: "GET", authentication: "collector bearer hint", readOnly: true, writes: false },
      { name: "collectorTelemetry", url: "https://usagemax.com/api/v1/telemetry/llm", method: "POST", authentication: "collector bearer", contentFree: true },
      { name: "collectorTraces", url: "https://usagemax.com/api/v1/traces", method: "POST", authentication: "collector bearer", contentFree: true },
      { name: "usageSnapshots", url: "https://usagemax.com/api/v2/usage/snapshots", method: "POST", authentication: "collector bearer", contentFree: true },
      { name: "sandboxValidate", url: "https://usagemax.com/api/v1/sandbox/validate", method: "POST", authentication: "none", writes: false },
    ],
    tools: [
      { name: "public_profile", protocol: "MCP", readOnly: true },
      { name: "leaderboard", protocol: "MCP", readOnly: true },
      { name: "network_stats", protocol: "MCP", readOnly: true },
      { name: "ask_site", protocol: "MCP", readOnly: true },
      { name: "usagemax_public_profile", protocol: "WebMCP", readOnly: true },
      { name: "usagemax_leaderboard", protocol: "WebMCP", readOnly: true },
      { name: "usagemax_network_stats", protocol: "WebMCP", readOnly: true },
      { name: "usagemax_ask", protocol: "WebMCP", readOnly: true },
    ],
    webmcp: {
      standard: "document.modelContext.registerTool",
      compatibilityFallback: "navigator.modelContext.registerTool",
      lifecycle: "AbortSignal passed as registerTool options.signal; abort unregisters the tools.",
      tools: ["usagemax_network_stats", "usagemax_leaderboard", "usagemax_public_profile", "usagemax_ask"],
      documentation: "https://usagemax.com/webmcp",
    },
    developerResources: [
      { name: "documentation", url: "https://usagemax.com/docs", mediaType: "text/html" },
      { name: "agentGuide", url: "https://usagemax.com/llms.txt", mediaType: "text/plain" },
      { name: "agentMode", url: "https://usagemax.com/agent.json", mediaType: "application/json" },
      { name: "agentResourceDiscovery", url: "https://usagemax.com/.well-known/ard.json", mediaType: "application/json" },
      { name: "aiCatalog", url: "https://usagemax.com/.well-known/ai-catalog.json", mediaType: "application/json" },
      { name: "apiCatalog", url: "https://usagemax.com/.well-known/api-catalog", mediaType: "application/linkset+json" },
      { name: "schemaFeed", url: "https://usagemax.com/schema-feed.jsonl", mediaType: "application/jsonl" },
      { name: "agentCard", url: "https://usagemax.com/.well-known/agent-card.json", mediaType: "application/json" },
      { name: "agentSkills", url: "https://usagemax.com/.well-known/agent-skills/index.json", mediaType: "application/json" },
      { name: "authentication", url: "https://usagemax.com/auth.md", mediaType: "text/markdown" },
      { name: "pricing", url: "https://usagemax.com/pricing.md", mediaType: "text/markdown" },
      { name: "profileMarkdown", url: "https://usagemax.com/profile.md", mediaType: "text/markdown", template: true, exampleUrl: "https://usagemax.com/symbiex.md", pathPattern: "/{handle}.md" },
      { name: "cliGuide", url: "https://usagemax.com/cli.md", mediaType: "text/markdown" },
      { name: "webmcp", url: "https://usagemax.com/webmcp", mediaType: "text/html" },
      { name: "webmcpMarkdown", url: "https://usagemax.com/webmcp.md", mediaType: "text/markdown" },
      { name: "agentPlugin", url: "https://raw.githubusercontent.com/SYMBaiEX/usagemax/main/plugin.json", mediaType: "application/json" },
      { name: "agentPluginOnDomain", url: "https://usagemax.com/plugin.json", mediaType: "application/json" },
      { name: "agentRules", url: "https://raw.githubusercontent.com/SYMBaiEX/usagemax/main/AGENTS.md", mediaType: "text/markdown" },
      { name: "mcpRegistry", url: "https://registry.modelcontextprotocol.io/v0.1/servers/io.github.SYMBaiEX%2Fusagemax/versions/latest", mediaType: "application/json" },
    ],
    resources: [
      { name: "openapi", url: "/openapi.json", contentType: "application/vnd.oai.openapi+json", authentication: "none", readOnly: true },
      { name: "mcp-discovery", url: "/.well-known/mcp", contentType: "application/json", authentication: "none", readOnly: true },
      { name: "a2a-agent-card", url: "/.well-known/agent-card.json", contentType: "application/json", authentication: "none", readOnly: true },
      { name: "agent-skills", url: "/.well-known/agent-skills/index.json", contentType: "application/json", authentication: "none", readOnly: true },
      { name: "pricing", url: "/pricing.md", contentType: "text/markdown", authentication: "none", readOnly: true },
      { name: "profileMarkdown", url: "/symbiex.md", contentType: "text/markdown", authentication: "none", readOnly: true, template: true, pathPattern: "/{handle}.md" },
      { name: "http-message-signatures-directory", url: "/.well-known/http-message-signatures-directory", contentType: "application/http-message-signatures-directory+json", authentication: "none", readOnly: true },
      { name: "agentRules", url: "https://raw.githubusercontent.com/SYMBaiEX/usagemax/main/AGENTS.md", contentType: "text/markdown", authentication: "none", readOnly: true },
      { name: "mcp-registry", url: "https://registry.modelcontextprotocol.io/v0.1/servers/io.github.SYMBaiEX%2Fusagemax/versions/latest", contentType: "application/json", authentication: "none", readOnly: true },
    ],
    protocols: {
      mcp: { endpoint: "/mcp", transport: "streamable-http", protocolVersion: "2025-06-18", authentication: "none", readOnly: true },
      a2a: { endpoint: "/a2a", transport: "json-rpc", authentication: "none", readOnly: true },
    },
    limits: {
      publicLeaderboardRows: 100,
      sandbox: { maxBytes: 16_384, maxEvents: 100, writes: false },
      mcp: { maxBodyBytes: 65_536, writes: false },
    },
    errors: { format: "application/json", schema: "/openapi.json#/components/schemas/Error", recovery: "/not-found.md" },
    links: {
      agent: "https://usagemax.com/agent.json",
      auth: "https://usagemax.com/auth.md",
      endpoint: "https://usagemax.com/openapi.json",
      integration: "https://usagemax.com/docs",
      llms: "https://usagemax.com/llms.txt",
      markdown: "/index.md",
      docs: "/docs",
      api: "/openapi.json",
      apiV1: "https://usagemax.com/api/v1",
      mcp: "/mcp",
      a2a: "/a2a",
      ask: "/ask",
      skills: "/.well-known/agent-skills/index.json",
      pricing: "https://usagemax.com/pricing.md",
      pricingPage: "/pricing",
      botAuthDirectory: "/.well-known/http-message-signatures-directory",
      mcpRegistry: "https://registry.modelcontextprotocol.io/v0.1/servers/io.github.SYMBaiEX%2Fusagemax/versions/latest",
      aiCatalog: "https://usagemax.com/.well-known/ai-catalog.json",
      apiCatalog: "https://usagemax.com/.well-known/api-catalog",
      schemaFeed: "https://usagemax.com/schema-feed.jsonl",
      agentRules: "https://raw.githubusercontent.com/SYMBaiEX/usagemax/main/AGENTS.md",
    },
    discovery: {
      llms: "https://usagemax.com/llms.txt",
      openapi: "https://usagemax.com/openapi.json",
      apiV1: "https://usagemax.com/api/v1",
      mcp: "https://usagemax.com/.well-known/mcp/server-card.json",
      a2a: "https://usagemax.com/.well-known/agent-card.json",
      authorizationServer: "https://usagemax.com/.well-known/oauth-authorization-server",
      protectedResource: "https://usagemax.com/.well-known/oauth-protected-resource",
      skills: "https://usagemax.com/.well-known/agent-skills/index.json",
      plugin: "https://raw.githubusercontent.com/SYMBaiEX/usagemax/main/plugin.json",
      pluginOnDomain: "https://usagemax.com/plugin.json",
      webmcp: "https://usagemax.com/webmcp",
      agentMode: "https://usagemax.com/agent.json",
      mcpRegistry: "https://registry.modelcontextprotocol.io/v0.1/servers/io.github.SYMBaiEX%2Fusagemax/versions/latest",
      aiCatalog: "https://usagemax.com/.well-known/ai-catalog.json",
      apiCatalog: "https://usagemax.com/.well-known/api-catalog",
      schemaFeed: "https://usagemax.com/schema-feed.jsonl",
      agentRules: "https://raw.githubusercontent.com/SYMBaiEX/usagemax/main/AGENTS.md",
    },
  };
}
