"use client";

import { memo, useMemo, useRef, useState } from "react";
import { Area, AreaChart, Bar, BarChart, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { calendarWindow, chartPalette, modelSeries, monthlySeries, otherColor, usageSeries, type ModelDay, type UsageDay } from "@/lib/chart-data";
import { compactNumber } from "@/lib/format";
import styles from "./usage-charts.module.css";

const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 }).format(value);
const dateLabel = (value: string) => new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`));
const axis = { axisLine: false, tickLine: false, tick: { fontSize: 11, fill: "#676c63" }, tickMargin: 10 };

function ChartTooltip({ active, payload, label, metric = "tokens" }: { active?: boolean; payload?: readonly { name?: string; value?: number | string; color?: string }[]; label?: string | number; metric?: "tokens" | "cost" }) {
  if (!active || !payload?.length) return null;
  const raw = String(label ?? "");
  return <div className={styles.tooltip} role="status"><strong>{/^\d{4}-\d{2}-\d{2}$/.test(raw) ? dateLabel(raw) : raw}</strong>{payload.filter(item => item.value !== null && item.value !== undefined).map((item, index) => <div key={`${item.name}-${index}`}><span><i style={{ background: item.color }} />{item.name}</span><b>{metric === "cost" ? money(Number(item.value)) : `${Number(item.value).toLocaleString()} tokens`}</b></div>)}</div>;
}

function DataTable({ data, metric }: { data: ReturnType<typeof usageSeries>; metric: "tokens" | "cost" }) {
  return <details className={styles.data}><summary>Explore the data <span>↗</span></summary><div tabIndex={0} role="region" aria-label="Chart source data"><table><caption>Source: UsageMax public profile snapshot · UTC days · {data[0]?.date} to {data.at(-1)?.date}</caption><thead><tr><th>Date</th><th>{metric === "cost" ? "Tracked cost (USD)" : "Tokens"}</th><th>Cost basis</th></tr></thead><tbody>{data.map(day => <tr key={day.date}><td>{day.date}</td><td>{day[metric] === null ? "Not reported" : metric === "cost" ? money(day.cost!) : day.tokens!.toLocaleString()}</td><td>{day.basis}</td></tr>)}</tbody></table></div></details>;
}

export const UsageTrend = memo(function UsageTrend({ rows }: { rows: UsageDay[] }) {
  const [days, setDays] = useState<30 | 90 | 365>(30);
  const [metric, setMetric] = useState<"tokens" | "cost">("tokens");
  const data = useMemo(() => usageSeries(rows, days), [rows, days]);
  const sum = data.reduce((total, day) => total + (day[metric] ?? 0), 0);
  const available = data.filter(day => day[metric] !== null).length;
  const color = metric === "tokens" ? "#ca512b" : "#397d86";
  return <figure className={styles.trend} id="usage-trend" aria-labelledby="usage-trend-title">
    <figcaption className={styles.heading}><div><span className={styles.kicker}>The shape of your work</span><h2 id="usage-trend-title">Your usage.<br /><em>In perspective.</em></h2></div><div className={styles.periods} role="group" aria-label="Usage time range">{([30, 90, 365] as const).map(value => <button key={value} type="button" aria-pressed={days === value} onClick={() => setDays(value)}>{value === 365 ? "1 year" : `${value} days`}</button>)}</div></figcaption>
    <div className={styles.readout}><strong>{metric === "tokens" ? compactNumber(sum, 2) : money(sum)}</strong><div className={styles.metricTabs} role="group" aria-label="Usage metric"><button type="button" aria-pressed={metric === "tokens"} onClick={() => setMetric("tokens")}>Tokens</button><button type="button" aria-pressed={metric === "cost"} onClick={() => setMetric("cost")}>Tracked cost</button></div><span>{available} reported days · UTC</span></div>
    {available ? <div className={styles.plot}><ResponsiveContainer width="100%" height="100%" debounce={80}><AreaChart data={data} margin={{ top: 16, right: 16, left: 0, bottom: 4 }} accessibilityLayer><XAxis {...axis} dataKey="date" tickFormatter={dateLabel} minTickGap={48} interval="preserveStartEnd" /><YAxis {...axis} width={54} domain={[0, "auto"]} tickFormatter={value => metric === "cost" ? `$${compactNumber(value)}` : compactNumber(value)} tickCount={4} /><Tooltip content={<ChartTooltip metric={metric} />} isAnimationActive={false} cursor={{ stroke: color, strokeOpacity: .3 }} /><Area dataKey={metric} name={metric === "tokens" ? "Tokens" : "Tracked cost"} type="linear" stroke={color} fill={color} fillOpacity={.12} strokeWidth={2} connectNulls={false} isAnimationActive={false} activeDot={{ r: 4, stroke: "#fff", strokeWidth: 2 }} /></AreaChart></ResponsiveContainer></div> : <p className={styles.empty}>No usage reported in this time range.</p>}
    <div className={styles.chartFoot}><span>{metric === "cost" ? "Reported / estimated cost, not a subscription bill." : "Daily token volume. Gaps mean no report, not zero usage."}</span><span>Hover or use ← → to inspect</span></div><DataTable data={data} metric={metric} />
  </figure>;
});

export const HeroSparkline = memo(function HeroSparkline({ rows }: { rows: UsageDay[] }) {
  const data = useMemo(() => usageSeries(rows, 30), [rows]);
  return <div className={styles.heroSpark}><div><span>Daily tokens</span><span>Last 30 days</span></div><ResponsiveContainer width="100%" height={88} debounce={80}><AreaChart data={data} margin={{ top: 8, right: 0, left: 0, bottom: 0 }} accessibilityLayer><YAxis hide domain={[0, "auto"]} /><XAxis hide dataKey="date" /><Tooltip content={<ChartTooltip />} isAnimationActive={false} /><Area dataKey="tokens" name="Tokens" stroke="#da623c" fill="#da623c" fillOpacity={.14} strokeWidth={2} type="linear" connectNulls={false} isAnimationActive={false} /></AreaChart></ResponsiveContainer></div>;
});

export const ModelFlow = memo(function ModelFlow({ rows }: { rows: ModelDay[] }) {
  const { data, models, hasOther } = useMemo(() => modelSeries(rows, 30), [rows]);
  return <figure className={styles.composition}><figcaption className={styles.heading}><div><span className={styles.kicker}>Your changing toolkit</span><h3>Models in motion.</h3></div><span className={styles.note}>Token composition · 30 days</span></figcaption>{models.length ? <><div className={styles.legend}>{models.map(model => <span key={model.id}><i style={{ background: model.color }} />{model.name}<small>{model.provider}</small></span>)}{hasOther ? <span><i style={{ background: otherColor }} />Other models</span> : null}</div><div className={styles.mixPlot}><ResponsiveContainer width="100%" height="100%" debounce={80}><AreaChart data={data} margin={{ top: 12, right: 12, left: 0, bottom: 4 }} accessibilityLayer><XAxis {...axis} dataKey="date" tickFormatter={dateLabel} interval="preserveStartEnd" minTickGap={48} /><YAxis {...axis} width={54} domain={[0, "auto"]} tickFormatter={value => compactNumber(value)} tickCount={3} /><Tooltip content={<ChartTooltip />} isAnimationActive={false} />{models.map(model => <Area key={model.id} dataKey={model.key} name={model.name} type="linear" stackId="tokens" fill={model.color} stroke={model.color} fillOpacity={.7} isAnimationActive={false} connectNulls={false} />)}{hasOther ? <Area dataKey="other" name="Other models" stackId="tokens" fill={otherColor} stroke={otherColor} fillOpacity={.7} type="linear" isAnimationActive={false} /> : null}</AreaChart></ResponsiveContainer></div><details className={styles.data}><summary>Explore model totals <span>↗</span></summary><div tabIndex={0} role="region" aria-label="Model chart source data"><table><caption>UsageMax daily model rollups · UTC · only reported model days</caption><thead><tr><th>Date</th>{models.map(model => <th key={model.id}>{model.name} ({model.provider})</th>)}{hasOther ? <th>Other</th> : null}<th>Total</th></tr></thead><tbody>{data.map(day => <tr key={String(day.date)}><td>{day.date}</td>{models.map(model => <td key={model.id}>{day[model.key] === null ? "Not reported" : Number(day[model.key]).toLocaleString()}</td>)}{hasOther ? <td>{day.other === null ? "Not reported" : Number(day.other).toLocaleString()}</td> : null}<td>{day.total === null ? "Not reported" : Number(day.total).toLocaleString()}</td></tr>)}</tbody></table></div></details></> : <p className={styles.empty}>Model-level daily history hasn’t been reported in this window.</p>}</figure>;
});

export const ActivityCalendar = memo(function ActivityCalendar({ rows }: { rows: UsageDay[] }) {
  const days = useMemo(() => calendarWindow(rows, 365), [rows]);
  const [selected, setSelected] = useState(days.length - 1);
  const buttons = useRef<Array<HTMLButtonElement | null>>([]);
  const maximum = Math.max(1, ...days.map(day => day.row?.totalTokens ?? 0));
  const active = days.filter(day => (day.row?.totalTokens ?? 0) > 0).length;
  const startOffset = new Date(`${days[0].date}T00:00:00Z`).getUTCDay();
  const selectedDay = days[selected];
  return <figure className={styles.calendar}><figcaption className={styles.heading}><div><span className={styles.kicker}>A year of showing up</span><h3>{active} active {active === 1 ? "day" : "days"}.</h3></div><span className={styles.note}>{dateLabel(days[0].date)} {days[0].date.slice(0, 4)} — {dateLabel(days.at(-1)!.date)} {days.at(-1)!.date.slice(0, 4)}</span></figcaption><div className={styles.calendarScroll}><div className={styles.calendarCells} role="group" aria-label="Daily token activity. Use arrow keys to explore days.">{Array.from({ length: startOffset }, (_, index) => <span key={`blank-${index}`} />)}{days.map((day, index) => { const level = day.row?.totalTokens ? Math.min(4, Math.ceil(day.row.totalTokens / maximum * 4)) : 0; return <button ref={node => { buttons.current[index] = node; }} key={day.date} type="button" tabIndex={index === selected ? 0 : -1} className={`${styles.cell} ${day.row ? styles[`level${level}`] : styles.unreported}`} aria-label={`${day.date}: ${day.row ? `${day.row.totalTokens.toLocaleString()} tokens` : "not reported"}`} aria-pressed={index === selected} onMouseEnter={() => setSelected(index)} onFocus={() => setSelected(index)} onClick={() => setSelected(index)} onKeyDown={event => { const delta = { ArrowRight: 7, ArrowLeft: -7, ArrowUp: -1, ArrowDown: 1 }[event.key]; if (delta !== undefined) { event.preventDefault(); const next = Math.max(0, Math.min(days.length - 1, index + delta)); setSelected(next); buttons.current[next]?.focus(); } }} />; })}</div></div><div className={styles.calendarFoot}><p role="status"><strong>{dateLabel(selectedDay.date)}</strong>{selectedDay.row ? `${selectedDay.row.totalTokens.toLocaleString()} tokens` : "No report for this day"}</p><div className={styles.heatLegend}><span>Less</span>{[0,1,2,3,4].map(level => <i key={level} className={styles[`level${level}`]} />)}<span>More</span><i className={styles.unreported} /><span>No report</span></div></div></figure>;
});

export const RhythmCharts = memo(function RhythmCharts({ rows }: { rows: UsageDay[] }) {
  const recent = useMemo(() => calendarWindow(rows, 365).flatMap(day => day.row ? [day.row] : []), [rows]);
  const weekdays = useMemo(() => { const labels = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]; const totals = labels.map(day => ({ day, tokens: 0, reported: false })); recent.forEach(row => { const day = totals[new Date(`${row.date}T00:00:00Z`).getUTCDay()]; day.tokens += row.totalTokens; day.reported = true; }); return [...totals.slice(1),totals[0]].map(day => ({ ...day, tokens: day.reported ? day.tokens : null })); }, [recent]);
  const months = useMemo(() => monthlySeries(recent), [recent]);
  return <div className={styles.rhythm}><figure><figcaption className={styles.heading}><div><span className={styles.kicker}>Your weekly rhythm</span><h3>Built on your schedule.</h3></div></figcaption><p className={styles.note}>{recent.length ? "Tokens by weekday · reported history in the last year" : "No weekday usage reported in the last year."}</p><div className={styles.rhythmPlot}><ResponsiveContainer width="100%" height="100%" debounce={80}><BarChart data={weekdays} margin={{ top: 12, right: 0, left: 0, bottom: 4 }} accessibilityLayer><XAxis {...axis} dataKey="day" /><YAxis {...axis} width={48} tickFormatter={value => compactNumber(value)} domain={[0,"auto"]} tickCount={3} /><Tooltip content={<ChartTooltip />} isAnimationActive={false} cursor={false} /><Bar dataKey="tokens" name="Tokens" maxBarSize={32} radius={[3,3,0,0]} isAnimationActive={false}>{weekdays.map(day => <Cell key={day.day} fill={day.day === "Sat" || day.day === "Sun" ? "#b5afa2" : chartPalette[1]} />)}</Bar></BarChart></ResponsiveContainer></div></figure><figure><figcaption className={styles.heading}><div><span className={styles.kicker}>The longer view</span><h3>Month by month.</h3></div></figcaption><p className={styles.note}>Tracked cost · last {months.length} reported months · current month may be partial</p><div className={styles.months}>{months.length ? months.map(month => <div key={month.month}><span>{new Intl.DateTimeFormat("en-US",{month:"short",year:"2-digit",timeZone:"UTC"}).format(new Date(`${month.month}-01T00:00:00Z`))}</span><i><b style={{width:`${month.cost / (Math.max(0,...months.map(row => row.cost)) || 1) * 100}%`}} /></i><strong>{money(month.cost)}</strong></div>) : <p>No monthly cost reported.</p>}</div></figure></div>;
});
